name: Code Coverage
on: [push, pull_request]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    env:
      DB_DATABASE: db_test
      DB_USER: root
      DB_PASSWORD: root
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: '1.16'

    - name: Set up Mysql
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_DATABASE }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        go mod download

    - name: Run Unit tests
      env:
        ROOT_PASSWORD: ${{ env.DB_PASSWORD }}
      run: |
        go test -race -covermode atomic -coverprofile=covprofile ./...

    - name: Install goveralls
      env:
        GO111MODULE: off
      run: go get github.com/mattn/goveralls
    # - name: Send coverage
    #   env:
    #     COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: goveralls -coverprofile=covprofile -service=github
    # or use shogo82148/actions-goveralls

    - name: Send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: covprofile